name: formatting

on:
  pull_request:
    branches:
      - v1
      - master
      - architecture

jobs:
  indentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: check indentation
        run: ./ci/check_indentation.sh

