name: shellcheck

on:
  pull_request:
    branches:
      - v1
      - master
      - architecture

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: shellcheck all files
        run: ./ci/shellcheck.sh

